application: predictionwiz-hrd
version: 1_6
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /stylesheets
  static_dir: stylesheets
  
- url: /js
  static_dir: js
  
- url: /css
  static_dir: css

- url: /adm/.*
  script: adm.app
  secure: always  
  
- url: /debug/.*
  script: adm.app
  login: admin    

- url: /webstore/.*
  script: webstore.py
  secure: always

- url: /api2demo
  static_dir: api2


  
- url: /.*
  script: main.app
  secure: always